baseURL = "https://alokkusingh.github.io/"
languageCode = "en-us"
title = "Alok Singh"
theme = "hugo-theme-prav"

# The settings below are used throughout the theme.
[params]
  title = "Alok Singh"
  tagline = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  author = "Alok Singh"
  authorImgPath = "/img/Alok.jpeg"
  authorBlurb = "Alok Singh | Technology Enthusiast"

[social]
  email = "mailto:alok.ku.singh@gmail.com"
  facebook = "https://www.facebook.com/alok.ku.singh"
  twitter = "http://twitter.com/alok_singh"
  github = "https://github.com/alokkusingh"
  linkedin = "https://www.linkedin.com/in/aloksingh24/"
  stackoverflow = "https://stackoverflow.com/users/1366503/alok-singh"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true